#   This script reads transport mode share statistics from (a) a baseline model and (b)
#   multiple simulation scenarios generated by different objective functions.
#   For each objective function, we have n scenarios, each representing a different PT network solution.
#   they are the top n results, and they are ordered by rank

#   The outputs are saved and the results visualised in a comparative plot.

library(tidyverse)
library(arrow)



# --- Configuration ---
# Define the objective function folders to be analyzed. Each string must match
# a folder name inside `../data/external/gtfs_optimisation/`.
objectives <- c("min_variance_stops") # Add other objectives here, e.g., c("min_variance_stops", "max_ridership")


# =============================================================================
## SECTION 2: DATA LOADING
# Read and combine data from the baseline and all specified scenario folders.
# =============================================================================

# --- Load and Prepare Baseline Data ---
# Read the final mode share statistics from the baseline scenario file.
# We then replicate this single baseline row for each objective function defined above.
# This allows us to use the baseline as a common starting point (Solution ID 0) for each trendline on the plot.
mode_share_original <- read_delim("../scenarios/basic/sample_1.00/modestats.csv", delim = ";") %>%
  slice_tail(n = 1) %>%
  crossing(objective = objectives) %>%
  mutate(solution_id = 0)


# --- Load Scenario Data ---
# Iterate over each objective to find its subfolders and read the corresponding data.
# `purrr::map_dfr` loops through the `objectives` vector and row-binds the results.
mode_share_scenarios <- purrr::map_dfr(objectives, function(current_objective) {

  # Define the path to the current objective's results folder.
  results_folder <- file.path("../data/external/gtfs_optimisation", current_objective)

  # Proceed only if the directory actually exists.
  if (!dir.exists(results_folder)) {
    warning(paste("Objective folder not found, skipping:", results_folder))
    return(NULL)
  }

  # Find all subfolders that match the "solution_[number]_gtfs" pattern.
  # The regex `^solution_\\d+_gtfs$` ensures we only match the correct folders.
  solution_folders <- list.dirs(results_folder, full.names = FALSE, recursive = FALSE)
  solution_folders <- solution_folders[grepl("^solution_\\d+_gtfs$", solution_folders)]

  # For the current objective, read the data from each of its solution folders.
  solutions_data <- purrr::map_dfr(solution_folders, function(folder_name) {
    file_path <- file.path(results_folder, folder_name, "output", "modestats.csv")

    if (!file.exists(file_path)) {
      warning(paste("File not found, skipping:", file_path))
      return(NULL)
    }

    # Read the last row of the modestats file.
    data <- read_delim(file_path, delim = ";", show_col_types = FALSE) %>%
      slice_tail(n = 1)

    # Extract the solution number from the folder name (e.g., "solution_05_gtfs" -> 5).
    solution_id <- as.numeric(stringr::str_extract(folder_name, "\\d+"))

    data %>% mutate(solution_id = solution_id)
  })

  # Add a column to identify which objective these solutions belong to.
  solutions_data %>% mutate(objective = current_objective)
})


# =============================================================================
## SECTION 3: DATA TRANSFORMATION
# Combine datasets and convert units for plotting.
# =============================================================================

# --- Combine Datasets ---
# Bind the replicated baseline data with all the scenario data into one data frame.
mode_share_combined <- bind_rows(mode_share_original, mode_share_scenarios)

# --- Convert to Percentages ---
# Transform mode share columns from fractions (e.g., 0.25) to percentages (e.g., 25).
# `across()` applies the same function to multiple columns efficiently.
mode_share_percent <- mode_share_combined %>%
  mutate(across(c(bike, car, car_passenger, pt, taxi, walk), ~ .x * 100))


# =============================================================================
## SECTION 4: VISUALIZATION
# Create a plot to compare the Public Transport (PT) mode share across solutions.
# =============================================================================

ggplot(mode_share_percent, aes(x = solution_id, y = pt, color = objective, group = objective)) +
  # Add a line to connect the points for each objective, showing the trend.
  geom_line(alpha = 0.6) +
  # Add points to mark the specific value for each solution.
  geom_point(size = 3) +
  # Customize plot titles, labels, and the legend title.
  labs(
    title = "Public Transport Mode Share by Solution",
    subtitle = "Comparing outcomes from different objective functions against the baseline (ID 0).",
    x = "Solution ID",
    y = "PT Mode Share (%)",
    caption = "Solution ID corresponds to its rank within each objective function.",
    color = "Objective Function"
  ) +
  # Format the y-axis labels to include a '%' sign.
  scale_y_continuous(labels = function(x) paste0(round(x, 1), "%")) +
  theme_bw() +
  # Adjust legend position for better readability.
  theme(legend.position = "bottom")
